//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerVerwaltung.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagerVerwaltung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Teil erstellen.
        /// </summary>
        public static string CreateNewPart {
            get {
                return ResourceManager.GetString("CreateNewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string NameOfPart {
            get {
                return ResourceManager.GetString("NameOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellmenge.
        /// </summary>
        public static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil bestellen.
        /// </summary>
        public static string OrderPart {
            get {
                return ResourceManager.GetString("OrderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis per Stück.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gewähltes Teil.
        /// </summary>
        public static string SelectedPart {
            get {
                return ResourceManager.GetString("SelectedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerbestand.
        /// </summary>
        public static string StorageAmount {
            get {
                return ResourceManager.GetString("StorageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit zum Zentrallager.
        /// </summary>
        public static string TimeNeeded {
            get {
                return ResourceManager.GetString("TimeNeeded", resourceCulture);
            }
        }
    }
}
